spring:
  application:
    name: cjava-matricula

  datasource:
    url: jdbc:h2:mem:escuela
    driver-class-name: org.h2.Driver
    username: admin
    password: desarrollo

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost